name: git to gcs

on:
  push:
    branches:
    - main
env:
  GCS_BUCKET: gitaction_to_gcs_jhk

jobs:
  deploy:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup gcloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.JSON_CREDENTIALS }}
    
    
    - name: Deploy
      run: |-
        gsutil -m rsync -R /home/runner/work/jhkim9403/gitaction-to-GCS gs://gitaction_to_gcs_jhk
