on:
  push:
    branches:
    - master
    
env:
  GCS_BUCKET: gitaction_to_gcs_jhk
    
steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup - gcloud / gsutil
    uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    with:
      service_account_key: ${{ secrets.GCS_SA_KEY }}
      project_id: test-jhk
      export_default_credentials: true
    
    
  - name: Deploy
    run: |-
      gsutil -m rsync -R output gs://gitaction_to_gcs_jh
