name: git to gcs

on:
  push:
    branches:
    - main
env:
  GCS_BUCKET: gitaction_to_gcs_jhk

jobs:
  deploy:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

  - name: Setup gcloud
    uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    with:
      service_account_key: ${{ secrets.GCS_SA_KEY }}
      project_id: test-jhk
      export_default_credentials: true
    
    
  - name: Deploy
    run: |-
      gsutil -m rsync -R jhkim9403/gitaction-to-GCS gs://gitaction_to_gcs_jhk
