on:
  push:
    branches:
    - master
    
    env:
  GCS_BUCKET: gitaction_to_gcs_jhk
    
steps:
  - name: Checkout
      uses: actions/checkout@v2

  - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGVzdC1qaGsi
        LAogICJwcml2YXRlX2tleV9pZCI6ICJmNDRkY2JmMTQzNzMxZmMwNzk3OTczOTBmNDI3YmExMWI2
        OGE2OTZiIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5N
        SUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUQ4Q3VWY0dB
        NDhDWld6XG51MlJGNGtvZUpGNUpvU3JwQ2RsQU9SRVRDVjRYUkNBTUdIcGl0Q0QxM0IxNmFUb3Qz
        aE82ODBmc3ZwKy9YZU41XG5XOHo2ZWgyeGIrdHhqYnVxbHJVWVQwaXZNZXAzU1h1TU5YME8va01T
        S3dZQUtyVGtGS2t4cE5XeFhTVW1YQUcxXG5CRm9LT3VhR2UrVlNzZ1dFRENIbGZLejdVZ2xUMVlE
        cjA0cU43UE5hZEc4Vjl1ZzFXdGoyYnJjSVF1UHJ5YmNCXG4zS0U5UXNXK21zSDZkN241cHVkZkJY
        c2NjREZVdnF4WW5Yc1hsQWIyMnNTS0lyODBIek80T3c5OFFWd001NDNjXG5rKzVQK1F3N2RVaTcr
        aU9ORmFUbklITGpTVkF1cEY5cmNXZ2tzOUhySG04L1FTMThReUs2Y0xJQ21rcitDMmZPXG5Nakdh
        VlpuWkFnTUJBQUVDZ2dFQUNlSWIveFhlNWdZS3NhRHZKRW5rdGVTZmNXUHhZTEMvRFFTSDJiOGY2
        a25rXG50MUMwNk42dkhiRDNVM1Bob1FlUXJyK29NZjJDR21FU1FOR2ptcTFUOFgrbDQvNm1yYUJx
        QXNWbUlGK1UxZjlpXG55YnRWdDNNck9tREhSQldvb1BwNTdYMU5GMTdEaklybVVyeTBVcXNmVzhY
        ck5zaE9ETkRrZWVFZkQ5NVdTUXdWXG43WXdadGQ2RExpZTVkQjBxNkg0d2haZWN2cWs0VStJZFI2
        Sk9MbWs3Q3d4UGJTUTBKeGdYNWRaU3FUOU1EVDVvXG53dGE2c3pnWGhjQXJud1VkQWpSZzNJcDZ4
        TDQycXFWRWxoNGpMQ1ovb05kY1hidlFrczVXWW9HeHBMWjMwQTEwXG5FN1o2TWlmbmVrQitMT2E1
        L3FvYlpPaUNPUjFhTWZKQ2tXY1AyeWl2Z1FLQmdRRC9QSmoyOVBHWnRjY29NMklSXG56Zit3UTVi
        UzEwbUExczkzWEk3blE1WTRjYnc5NExuUnpJK09oUys0UUszRVR6TXh4MGh2RXNqZjJjcE51RGVE
        XG5ETVNrQ3VqcWZRWGhCb3dBaEpBSjdEMzh4QTVwVGR3QytITitwL0o3MUt2TzI3Rjhsc09oeDF1
        aWdTWmUvWCtxXG5uQTJhSEJKTFJMbGIrU2dOYjNieW5LejVnUUtCZ1FEOHk5cGlZL09jMFVCL2hU
        RW9SWm45ZVlONGgzNXpMQXRhXG5sRmtXcnZ2RGMzWENtZzhRZ05meFJSbGpVZWhzcE44a245b25s
        SDllOXI0clhmU0wwN3pUV1Z4VEJhOHJHT1NHXG5pMEgyRVU1NTlZcVcyY1dXalF2c0hKU0VXSzVR
        RXc1ZCtnUlFDNU1yV2Z2T2ErRFRhZDR3a2JvcjlNV1lmRXRqXG5SUHJ6RDhqY1dRS0JnQ2VJbEV6
        VUhjUG9Nd1BZQ1oybVlhOUVtTXpwaWJvS0M3SjZSS3d2Zk1vYlc4UGQxZ3BYXG4rL2hnU3Nib1Jj
        SDlYbm1jVzJ6UTVRby9LcVdsSGZ3UGN6blJjc2czT3p6aWpiYmEwWkNuNWVZTDNBdVZncmwzXG5F
        RFNUQU8wTFFOMVdqQVEzT2ZBSjkvaVF0b2ZLRGdjNENxZFBKOG8reDlNbUlYMExRY3BNV0VLQkFv
        R0JBTTRmXG5kZEMyQ1FRN3hxaHp0TkpPZGpJc3ExdFN0M00zWFlhYzRVdFNvR3dNcjk5ZCtKeVBR
        Z1F6UUhFd2J5QnZDcGQxXG5VODdrRVRzZ1c0MUd6Y2haZkdTa1AxaGVrU2JGNUVna01rTnVkeHVR
        YjFGeS9kNDA0WnpDN1FKQXdOai93TDQxXG54dUJ4bjYxQWNNWXVSaUo3OXpTSkRsRWJBeWJEYWtE
        bUZPeXRXU3o1QW9HQkFMS3YyNHJMKzRuY3dJSGRUYjEwXG5hTi9VZDJxanByKzlkTVV2YmlsZ3ZO
        d1JpR1NYTEVHbkpCMmRidjZXUm1MUFpNaFVpU1Q5Vm5Ha05EMmtMaXBKXG5PWklCRzBaQnFtU2Q4
        RUlrMTlDZjdXRFduT2t5YW54ajFoQmplRzBSNmJLRmx0bVJvek5IYjR0RU44VjBZdWNlXG5vZE9n
        VmJXZXJMdXdQVmhCR0lXdTRyelBcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNs
        aWVudF9lbWFpbCI6ICJnaXRhY3Rpb25AdGVzdC1qaGsuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20i
        LAogICJjbGllbnRfaWQiOiAiMTE2NTA4MzkxMjU5NTAwNTAxMzEzIiwKICAiYXV0aF91cmkiOiAi
        aHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmki
        OiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVy
        X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2Nl
        cnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5j
        b20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9naXRhY3Rpb24lNDB0ZXN0LWpoay5pYW0uZ3NlcnZp
        Y2VhY2NvdW50LmNvbSIKfQo=
    project_id: test-jhk
    export_default_credentials: true
    
    
- name: Deploy
    run: |-gsutil -m rsync -R output gs://gitaction_to_gcs_jhk
