on:
  push:
    branches:
    - master
    
env:
  GCS_BUCKET: gitaction_to_gcs_jhk
    
steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}
    project_id: ${{ secrets.GCS_PROJECT_ID }}
    export_default_credentials: true
    
    
- name: Deploy
    run: |-gsutil -m rsync -R output gs://gitaction_to_gcs_jhk
